# Generated by Django 3.2.4 on 2021-06-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
