# Generated by Django 3.2.4 on 2021-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0008_academicyear20_21'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear20_21',
            name='eventdescription',
            field=models.CharField(default='events', max_length=1000),
        ),
        migrations.AlterField(
            model_name='academicyear20_21',
            name='eventnumber',
            field=models.CharField(max_length=10),
        ),
    ]
