# Generated by Django 3.2.4 on 2021-06-22 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0009_auto_20210623_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear20_21',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
