# Generated by Django 3.2.4 on 2021-06-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0010_academicyear20_21_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnername', models.CharField(max_length=30)),
                ('yearofstudy', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('eventno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSI.academicyear20_21')),
            ],
        ),
    ]
