# Generated by Django 3.2.4 on 2021-06-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0011_winners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winners',
            old_name='winnername',
            new_name='winnername1',
        ),
    ]
