# Generated by Django 3.2.4 on 2021-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0012_rename_winnername_winners_winnername1'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='winnername2',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='winners',
            name='winnername3',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='winners',
            name='winnername1',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
