# Generated by Django 3.2.4 on 2021-06-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0013_auto_20210625_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='section',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='yearofstudy',
        ),
        migrations.AddField(
            model_name='winners',
            name='section1',
            field=models.CharField(default='Section', max_length=10),
        ),
        migrations.AddField(
            model_name='winners',
            name='section2',
            field=models.CharField(default='Section', max_length=10),
        ),
        migrations.AddField(
            model_name='winners',
            name='section3',
            field=models.CharField(default='Section', max_length=10),
        ),
        migrations.AddField(
            model_name='winners',
            name='yearofstudy1',
            field=models.CharField(default='YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='winners',
            name='yearofstudy2',
            field=models.CharField(default='YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='winners',
            name='yearofstudy3',
            field=models.CharField(default='YEAR', max_length=20),
        ),
    ]
