# Generated by Django 3.2.4 on 2021-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0016_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationforevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('year', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('dateandtime', models.DateTimeField()),
            ],
        ),
    ]
