# Generated by Django 3.2.4 on 2021-07-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0017_registrationforevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforevents',
            name='rollnumber',
            field=models.CharField(default='18kb1a05', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationforevents',
            name='dateandtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
