# Generated by Django 3.2.4 on 2021-07-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0018_auto_20210701_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
